# build ruby oas client from open file

name: Build client

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      GEM_FOLDER: "generated/ruby"
      GEM_NAME: "autosde_openapi_client"
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      - name: extract current gem version
        run: |
          sudo gem install bump
          cd $GEM_FOLDER
          current_version=$(bump current)
          echo "current version: $current_version"
          next_version=$(bump show-next patch)
          echo "next version: $next_version"
          echo "NEXT_VERSION=$next_version" >> $GITHUB_ENV

      - name: generate ruby oas client
        run: |
          docker run \
          -v $GITHUB_WORKSPACE:/local \
          -v $GITHUB_WORKSPACE/generated/ruby:/local_out \
          --name ruby-oas-generator \
          --rm \
          openapitools/openapi-generator-cli:v5.0.0 generate \
          -i /local/site_manager_oas.json -g ruby -o /local_out \
          --skip-validate-spec \
          --additional-properties=gemName=$GEM_NAME \
          --additional-properties=moduleName=AutosdeOpenapiClient \
          --additional-properties=gemLicense=Apache-V2 

      - name: bump version (patch only)
        run: |
          cd $GEM_FOLDER
          sudo gem install bump
          sudo bump  set $NEXT_VERSION --replace-in lib/autosde_openapi_client/version.rb

      - name: Commit files
        run: |
          git config --local user.email "inner-autosde@users.noreply.github.com"
          git config --local user.name "Autosde"
          git add -A
          git commit --allow-empty -m "update"
      - name: Push changes to github
        run: |
          remote_repo="https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"
          git push "${remote_repo}" -f

      - name: build and push gem
        run: |
          cd $GEM_FOLDER
          sudo gem build ${GEM_NAME}
          echo "Setting up gem credentials..."
          set +x
          mkdir -p ~/.gem

          cat << EOF > ~/.gem/credentials
          ---
          :github: Bearer ${{ secrets.GITHUB_TOKEN }}
          :rubygems_api_key: ${{ secrets.RUBYGEMS_API_KEY }}
          EOF

          chmod 0600 ~/.gem/credentials
          set -x

          gem push "${GEM_NAME}-${NEXT_VERSION}.gem"
